# Preface {.unnumbered}

The foundations of adult health and wellbeing have their origins early in life, often measured by children's early growth and development [@clark2020]. Growth standards established by the World Health Organization (WHO) have been adopted globally, and are used as indices and targets for improvement. For example, in 2018, 219 million children under 5 years of age (21.9%) were stunted (height for age \< -2 standard deviations of the WHO growth standards) [@unicef2019]. Stunting early in life has been associated with negative childhood development, academic achievement, and adult productivity. In the absence of direct population-based metrics for childhood development, stunting and poverty have been used as proxy indicators to estimate the number of children not reaching their developmental potential [@lu2016].

Although stunting and poverty have been effective indicators and have contributed to advances in global childhood development policies and programs [@black2017], they lack the sensitivity to measure changes associated with programmatic interventions. Early childhood development is a latent construct comprised of an ordinal sequence of developmental domains (motor, language, cognitive, personal-social). A valid and easily interpretable metric is needed to interpret the underlying latent construct of early childhood development that can represent change and is comparable across cultures and contexts. The D-score booklet I [Turning milestones into measurement](https://d-score.org/dbook1) in this series showed that the D-score (Developmental score) meets those criteria.

The present volume, [Tuning instruments to unity](https://d-score.org/dbook2), deals with the problem of how to define and calculate the D-score from data obtained from multiple studies and multiple instruments. After harmonizing longitudinal measures of childhood development among over 36,000 children from 11 countries [@Weber2019], the statistical analysis produced a D-score scale with interval qualities that can reflect change over time and enable within and across country comparisons. In addition, the D-score is responsive to environmental conditions that may impact children's development, ranging from community programs and policies to macro-level conditions from migration, inequities, or climate. Applied to populations, direct metrics of children's early growth and development assess the current status of the population's health and well-being, establish predictions of future health and well-being, and provide opportunities to measure changes. Thus, applying the D-score to the early development of children extends to populations and society as a whole.

> Maureen Black (July, 2020)
